### ISSUE TITLE
Punchlist for Washoe trigger

### ISSUE THREAD

**Issue by bradical** [nadirayasmeen/spectate-publish-trigger#5]
Backlog in order of importance:
- [x] Get working in their development instance as quickly as possible
- [ ] Get working in their production instance as quickly as possible
- [x] **Make it fast**. Publish triggers run and each every publish regardless of Site so this thing needs to "get to no" (or skip non-pertinent jobs) as quickly as possible hopefully avoiding any API calls. #7
- [x] Ensure no duplication of emails #7
- [ ] Fix email rendering issues #8
- [x] Implement "Save as draft" and "Schedule send" #1
- [x] Does Test Emails need to do anything? Has it been tested? @nadirayasmeen 
- [x] Their DD in their Dev instance has an option "Include body in email". Do we need to be doing something with this in the trigger? @nadirayasmeen @pennyharding
- [x] Code cleanup #2 #6
## Checklist for prod deployment
- Copy over the `spectate-email-publish-trigger-1.0.jar`, `commons-lang3-3.3.2.jar` and `jsoup-1.8.1.jar` dependencies to `WEB-INF/lib`. They'll need to keep track of these files and ensure they're always added to any new release
- Set-up the publish trigger in their configuration with the classname and the params: `url`, `apiKey` (of the Spectate user who will create the emails), `pageConfigurationId` (of the page configuration in the config set for which this will be applicable), `user`/`pass` (for the user to authenticate to the API and WS operations)
- Add in the new DD field value for `send` field to keep track of "already sent" status with a value: `Sent to Spectate already`
- Test publishing one of these pages with the `send` status sent to "Draft".
- Publish it again to ensure it's being appropriately skipped on second pass.

/cc @pennyharding @nadirayasmeen

**Comment by bradical** [comment]
I was able to get it to [create an Email](https://my.spectate.com/marketing/emails/2515) in their dev environment. Going to do a little more testing in dev before asking them to port it to prod.

We're still hitting some issues with the code for #7 not working because the Edit API is broken. We'll continue to work on that locally.

**Comment by nadirayasmeen** [comment]
The test email address field is essentially the same as the "test email" field in Spectate. It adds the given email values into Spectate's "Test Email" field. I think this is to send emails to people not part of a campaign.

**Comment by bradical** [comment]
Yes, that's what the field is for. I'm just wondering what the intention of the field is in Cascade. Are they expecting it to send automatically? That field won't be used in Spectate until you hit "Send test email" so they'd have to do it manually. @pennyharding any ideas?

**Comment by pennyharding** [comment]
I'd say requiring them to do it manually would be fine and just populate the field.

**Comment by bradical** [comment]
Hey @pennyharding, we also noticed a field in their DD called: "Include body in email" and we're trying to figure out if that's something our trigger needs to do something with or if that just affects the rendered/published page that the trigger consumes? @nadirayasmeen  and I weren't sure. Thanks!

**Comment by pennyharding** [comment]
Just affects the render that you are pulling

**Comment by pennyharding** [comment]
That's handled in velocity

**Comment by bradical** [comment]
Thanks! In that case, we just have three things remaining:
- Test out changes to skip non-relevant publishes or publishes of pages that have already been sent to Spectate in their dev instance #7 
- Port everything to their prod to make sure it still works
- (Optional) A bit of code cleanup and refactoring #2 #6

**Comment by bradical** [comment]
Did a [test publish](https://my.spectate.com/marketing/emails/2536) and @pennyharding pointed that the image and "More announcements" text are being combined together. It [looks ok in the rendered email](https://my.spectate.com/marketing/emails/2536/view) that was sent to me from Spectate but looks incorrect in my Inbox in Mailbox on both my Mac and my Phone:

![image](https://cloud.githubusercontent.com/assets/191132/6581619/8add807c-c72e-11e4-84a5-b8ed014b82d9.png)

@pennyharding which mail client were you using?

Other issues that I saw when viewing the email in Gmail include:
- A broken facebook link image in the top-left. Again looks fine in rendered email but incorrect in my Inbox
- An extra `< /td>` tag floating at the bottom

![image](https://cloud.githubusercontent.com/assets/191132/6581670/ef40d64a-c72e-11e4-8910-23bf59b6df0d.png)

**Comment by pennyharding** [comment]
Gmail.

On Tue, Mar 10, 2015 at 2:08 PM, Bradley Wagner notifications@github.com
wrote:

> Did a test publish https://my.spectate.com/marketing/emails/2536 and
> @pennyharding https://github.com/pennyharding pointed that the image
> and "More announcements" text are being combined together. It looks ok in
> the rendered email https://my.spectate.com/marketing/emails/2536/view
> that was sent to me from Spectate but looks incorrect in my Inbox in
> Mailbox on both my Mac and my Phone:
> ![image](
> https://cloud.githubusercontent.com/assets/191132/6581619/8add807c-c72e-11e4-84a5-b8ed014b82d9.png
> 
> @pennyharding https://github.com/pennyharding which mail client were
> you using?
> 
> Other issues that I saw when viewing the email in Gmail include:
> - A broken facebook link image in the top-left. Again looks fine in
>   rendered email but incorrect in my Inbox
> - An extra < /td> tag floating at the bottom
> 
> [image: image]
> https://cloud.githubusercontent.com/assets/191132/6581670/ef40d64a-c72e-11e4-8910-23bf59b6df0d.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nadirayasmeen/spectate-publish-trigger/issues/5#issuecomment-78112830
> .

## 

Penny Kronz
Services Director
678.904.6900 ext 255

Hannon Hill - Amplify Your Content
http://www.hannonhill.com

**Comment by nadirayasmeen** [comment]
Weird, my gmail renders the email like 
![screen shot 2015-03-10 at 11 11 58 am](https://cloud.githubusercontent.com/assets/2363709/6581804/5e7e1414-c716-11e4-909e-6a96abe7a93d.png)

The "More Announcements" looks a little wonky but no extra tags

**Comment by pennyharding** [comment]
I didn't get any extra tags either.

On Tue, Mar 10, 2015 at 2:13 PM, Nadira Yasmeen notifications@github.com
wrote:

> Weird, my gmail renders the email like
> [image: screen shot 2015-03-10 at 11 11 58 am]
> https://cloud.githubusercontent.com/assets/2363709/6581804/5e7e1414-c716-11e4-909e-6a96abe7a93d.png
> 
> The "More Announcements" looks a little wonky but no extra tags
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/nadirayasmeen/spectate-publish-trigger/issues/5#issuecomment-78113686
> .

## 

Penny Kronz
Services Director
678.904.6900 ext 255

Hannon Hill - Amplify Your Content
http://www.hannonhill.com

**Comment by bradical** [comment]
Moved discussion to #8

**Comment by bradical** [comment]
Quick update here.
- We recently deployed a build of 3d9d14f0ba9efdd6ce358ac90f220df3fa6d1cca to their dev server and have been testing that.
- We'll need to continue to test what we've got in Dev and also involve Barbara (and whoever else) in that effort on their end.
- Everything from our punchlist except for #2 is complete at this point though some of the newer code could benefit from more logging. @nadirayasmeen is working on #2 which involves refactoring some of our code.
- I'll update the documentation in the issue description that details how to port this to prod.

After that, it's just testing, testing, testing in Dev and then porting to Prod and testing a bit more.

**Comment by bradical** [comment]
Quick update for Fri, 3/13/2015:
- We're working on a fix to email rendering hannonhill/Spectate#2306 that will address the weird character issues we've seen.
- We've made all of the revisions and code cleanup changes to the trigger itself that we're going to
- We're waiting on Washoe to finish their testing of this in Dev before helping them migrate it to Production using the "Checklist for prod deployment" from this issue's description.

@pennyharding @nadirayasmeen -- I'm going to call this one Done For Now from our end. Let me know if I've missing anything.

Thanks!
